// A correlated cluster of alerts. This is the actual unit of work.
//
// It is the core bet of the product: an operator should be handed a short list of
// incidents with hypotheses, not a long list of alerts. Everything prefixed ai_ is
// generated by fn_claude and is advisory. Confidence is always surfaced, and the evidence
// the model used is stored alongside, so a human can check its reasoning.
table incident {
  auth = false

  schema {
    int id
    timestamp created_at?=now

    text title filters=trim

    enum severity?=warning {
      values = ["critical", "warning", "info"]
    }

    enum state?=open {
      values = ["open", "investigating", "mitigated", "resolved"]
    }

    int site_id? {
      table = "site"
    }

    int device_count?=0
    int alert_count?=0

    timestamp opened_at?=now
    timestamp? resolved_at?

    int assigned_to? {
      table = "user"
    }

    // What grouped these alerts, e.g. "site:1|type:2|metric:temp_c".
    text correlation_key? filters=trim
    text correlation_reason?

    text ai_summary?
    text ai_root_cause?
    decimal? ai_confidence?
    json ai_remediation?
    json ai_evidence?
    text ai_model? filters=trim
    timestamp? ai_generated_at?
    text ai_postmortem?
    bool ai_fallback_used?=false
  }

  index = [
    {type: "primary", field: [{name: "id"}]}
    {type: "btree", field: [{name: "state"}]}
    {type: "btree", field: [{name: "severity"}]}
    {type: "btree", field: [{name: "site_id"}]}
    {type: "btree", field: [{name: "opened_at", op: "desc"}]}
    {type: "btree", field: [{name: "correlation_key", op: "asc"}]}
  ]

  tags = ["nerve"]
  guid = "AgPHD5PI9mkaFm_hOmAVdeZRq4Q"
}
